version: "3.8"

services:
  nginx:
    image: "jwilder/nginx-proxy:alpine"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      frontend:
      backend:

  ui:
    depends_on:
      - nginx
    expose:
      - "80"
    build:
      context: "."
      dockerfile: Dockerfile.dev
    environment:
      - VIRTUAL_HOST=scheduler.localhost
      - VIRTUAL_PORT=80
    hostname: scheduler.localhost
    volumes:
      - ./:/app:delegated
      - /app/node_modules/
    networks:
      frontend:
      backend:
        aliases:
          - scheduler.localhost

networks:
  frontend:
  backend:
