version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - |
        npm run build --mode=production --dest=dist | tee build.log
        if grep -E "Compiled with .+ warning" build.log; then
          exit 1
        fi
  post_build:
    commands:
      - echo Build completed on `date`
